name: Continuous Integration (CI)

on:
  push:
    branches:
      # We can define multiple branches as well
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Defines the type of runner the job runs on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v3

      - name: Set up NodeJS environment
        uses: actions/setup-node@v2
        with:
          node-version: 18

      # Consider this as an add on to optimize the execution of actions
      - name: Cache node modules
        id: cache-yarn
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install package dependencies
        run: yarn

      - name: Check linting and formatting
        # Custom script for checking the linting and formatting being in place
        run: yarn eslint 'src/**'

      # Run test cases and this could ensure minimum coverage as well if set
      - name: Execute test cases
        run: yarn test:ci

      - name: Coveralls
        uses: coverallsapp/github-action@v2

  cypress-run:
    runs-on: ubuntu-latest
    needs: build

    container: cypress/browsers:chrome69

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: yarn test:cypress:ci
          browser: chrome
